//
//  AIInsightRepositoryProtocol.swift
//  Bloom
//
//  Repository protocol for AI-powered insights
//

import Foundation

/// Errors that can occur during AI insight operations
enum AIInsightError: Error, LocalizedError {
    case generationFailed
    case rateLimitExceeded
    case networkError
    case invalidInput
    case serviceUnavailable

    var errorDescription: String? {
        switch self {
        case .generationFailed:
            return "Failed to generate insight"
        case .rateLimitExceeded:
            return "You've reached your weekly insight limit. Upgrade to premium for unlimited insights."
        case .networkError:
            return "Network error. Please check your connection"
        case .invalidInput:
            return "Invalid input for insight generation"
        case .serviceUnavailable:
            return "AI service is temporarily unavailable"
        }
    }
}

/// Protocol defining AI insight repository operations
protocol AIInsightRepositoryProtocol: Sendable {
    /// Generates a personalized insight for a check-in
    func generateInsight(for checkIn: DailyCheckIn, userGoals: [WellnessGoalType]) async throws -> String

    /// Generates weekly pattern analysis
    func generateWeeklyAnalysis(checkIns: [DailyCheckIn], habits: [Habit]) async throws -> WeeklyAnalysis

    /// Sends a message in the AI chat and gets a response
    func chat(message: String, context: ChatContext) async throws -> String

    /// Gets personalized tips based on user data
    func getPersonalizedTips(for user: UserProfile, recentCheckIns: [DailyCheckIn]) async throws -> [WellnessTip]

    /// Checks remaining free insights for the week
    func getRemainingFreeInsights(userId: String) async throws -> Int
}

/// Weekly analysis generated by AI
struct WeeklyAnalysis {
    let summary: String
    let moodInsights: String
    let energyInsights: String
    let sleepInsights: String
    let recommendations: [String]
    let highlightHabit: String?
    let generatedAt: Date
}

/// Context for AI chat conversations
struct ChatContext {
    let userId: String
    let userGoals: [WellnessGoalType]
    let recentCheckIns: [DailyCheckIn]
    let conversationHistory: [ChatMessage]
}

/// A message in the chat history
struct ChatMessage: Identifiable {
    let id: String
    let role: Role
    let content: String
    let timestamp: Date

    enum Role {
        case user
        case assistant
    }
}

/// A wellness tip generated by AI
struct WellnessTip: Identifiable {
    let id: String
    let title: String
    let description: String
    let category: WellnessGoalType
    let actionable: String
}
